### ISSUE TITLE
Crash when connecting to the world

### ISSUE THREAD

**Issue by tyukara** [Hephaestus-Dev/Atmosfera#7]
Hello.
When using atmosfera 1.3.0 in minecraft 1.16.2, it crashes while connecting to the world.
The crash log is shown below.

single play
https://paste.ee/p/aWBJZ

multiplay
https://paste.ee/p/sc8A5

**Comment by Hephaestus-Dev** [comment]
Fixed in version [1.3.1](https://www.curseforge.com/minecraft/mc-mods/atmosfera/files/3050694).
