### ISSUE TITLE
Crash with new 1.16.2 game

### ISSUE THREAD

**Issue by Chucky2401** [Hephaestus-Dev/Atmosfera#9]
Hello,
I created a new profile with:
+ Minecraft 1.16.2
+ Fabric Loader 0.10.0
+ Fabric API 0.19.0
+ Optifabric 1.5.0
+ Optifine 1.16.2 HD U G3
+ ModMenu 1.14.6
+ **Atmosfera 1.3.2**

I get this error before the game launch:

`Could not find required mod: atmosfera requires {cloth-config2 @ [*]}`

I tried with this mod too:
+ Minecraft 1.16.2
+ Fabric Loader 0.10.0
+ Fabric API 0.20.1
+ ModMenu 1.14.6
+ **Atmosfera 1.3.2**

And I get the same error. Could you help me with this error? A lot of my friends have the same error.

I mad a lot of tests with different version of everything (Fabric Loader, Fabric API, without mods and different version of Atmosfera), about twenty tests.

For information, a profile in MC 1.15.2 migrated to 1.16.2 works like a charm, I don't know why.

Some friends use the 1.2.2 version that crash after loading with the Mojang logo, and replace by the 1.3.2 version and it works. This is not my case.

When I tried with the version 1.2.2 here the log: https://pastebin.com/Hsu25HGr

And here with version 1.3.2, Loader 0.10.0 and API 0.20.1 with the above error: https://pastebin.com/eSYegrHB

Thank you for your help.

**Comment by Chucky2401** [comment]
I think I understand...

If I launch the game with only Atmosfera (without Fabric API) I get this error message
![Imgur](https://i.imgur.com/Pp5st9U.png)

So, I installed the mod **Cloth Config API (Fabric)** and it works now!

But, on your CurseForge page you don't mention this new dependance.

Could you confirm I right?

**Comment by Hephaestus-Dev** [comment]
Sorry about that! I used to bundle Cloth Config, but decided not to with the new version. I'll make this clearer on CurseForge.

**Comment by Chucky2401** [comment]
Thank you for the details
